name: Deploy to Unikraft Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      - name: Install KraftKit
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
          if [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi

          VERSION=$(curl -sL https://api.github.com/repos/unikraft/kraftkit/releases/latest | grep '"tag_name"' | cut -d'"' -f4)

          wget -q "https://github.com/unikraft/kraftkit/releases/download/${VERSION}/kraft_${VERSION}_linux_${ARCH}.tar.gz"
          tar xzf "kraft_${VERSION}_linux_${ARCH}.tar.gz"
          chmod +x kraft
          sudo mv kraft /usr/local/bin/
      
      - run: bun install
      - run: bun run build
      
      - name: Deploy
        env:
          KRAFTCLOUD_TOKEN: ${{ secrets.UKC_TOKEN }}
        run: kraft cloud deploy -p 443:3000 -M 2048 --replace .
