name: Deploy to Unikraft Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      - name: Install KraftKit
        run: |
          wget -q https://github.com/unikraft/kraftkit/releases/download/v0.12.3/kraft_linux_amd64 -O kraft
          chmod +x kraft
          sudo mv kraft /usr/local/bin/
      
      - run: bun install
      - run: bun run build
      
      - name: Deploy
        env:
          KRAFTCLOUD_TOKEN: ${{ secrets.UKC_TOKEN }}
        run: kraft cloud deploy -p 443:3000 -M 2048 --replace .
